import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import {
  readinessProfileSchema,
  readinessReceiptSchema,
  violationSchema,
  type ReadinessProfile,
  type Violation
} from "../schemas/core.js";

export interface SuiteProofMissionSummary {
  missionId: string;
  title: string;
  domain: string;
  artifactDir: string;
  proofLoop: string;
  before: {
    verdict: string;
    score: number;
    violations: number;
  };
  after: {
    verdict: string;
    score: number;
    violations: number;
    evidenceRefs: string[];
  };
}

export interface SuiteProofSummary {
  status: "PASS" | "FAIL";
  mode: "fixture";
  mutation: false;
  suiteId: string;
  suiteTitle: string;
  suitePath: string;
  missionCount: number;
  domains: string[];
  totals: {
    failToPass: number;
    readyAfterPatch: number;
    evidenceRefs: number;
  };
  missions: SuiteProofMissionSummary[];
}

interface SuiteCompilerRuleOutcome {
  ruleId: string;
  severity: string;
  source: string;
  beforeViolations: number;
  afterViolations: number;
  resolved: boolean;
  contractRefs: string[];
  missionRefs: string[];
  evidenceRefs: string[];
  rationale: string;
}

interface SuiteCompilerMissionDiagnostics {
  missionId: string;
  title: string;
  domain: string;
  artifactDir: string;
  proofLoop: string;
  readinessProfileId: string;
  contractRef: ReadinessProfile["contractRef"];
  deploymentSignals: ReadinessProfile["deploymentSignals"];
  before: {
    verdict: string;
    score: number;
    violations: number;
    traceRefs: number;
    evidenceRefs: number;
  };
  after: {
    verdict: string;
    score: number;
    violations: number;
    traceRefs: number;
    evidenceRefs: number;
  };
  activeRules: number;
  ruleOutcomes: SuiteCompilerRuleOutcome[];
}

interface SuiteCompilerDiagnostics {
  source: "splunkready-suite-compiler-diagnostics";
  generatedAt: string;
  compiler: "Agent Readiness Compiler";
  status: SuiteProofSummary["status"];
  mode: "fixture";
  mutation: false;
  suite: {
    id: string;
    title: string;
    path: string;
    missionCount: number;
    domains: string[];
  };
  passFailAuthority: "deterministic-rule-engine";
  advisoryOnly: {
    allowedRoles: string[];
    prohibitedRoles: string[];
  };
  totals: {
    activeRules: number;
    beforeViolations: number;
    afterViolations: number;
    resolvedRules: number;
    evidenceRefsAfterPatch: number;
    traceRefsAfterPatch: number;
  };
  missions: SuiteCompilerMissionDiagnostics[];
}

const readJson = async <T>(filePath: string, label: string): Promise<T> => {
  try {
    return JSON.parse(await readFile(filePath, "utf8")) as T;
  } catch {
    throw new Error(`Unable to read ${label} at ${filePath}. Run the prerequisite CLI command first.`);
  }
};

const writeJson = async (filePath: string, value: unknown): Promise<void> => {
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
};

const writeText = async (filePath: string, value: string): Promise<void> => {
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, value.endsWith("\n") ? value : `${value}\n`, "utf8");
};

const uniqueStrings = (values: string[]): string[] => [...new Set(values.filter((value) => value.length > 0))].sort();

const countViolationsByRule = (violations: Violation[]): Map<string, number> => {
  const counts = new Map<string, number>();

  for (const violation of violations) {
    counts.set(violation.ruleId, (counts.get(violation.ruleId) ?? 0) + 1);
  }

  return counts;
};

const diagnosticsMarkdown = (diagnostics: SuiteCompilerDiagnostics): string => {
  const rows = diagnostics.missions
    .flatMap((mission) =>
      mission.ruleOutcomes.map(
        (rule) =>
          `| \`${mission.missionId}\` | \`${rule.ruleId}\` | ${rule.severity} | ${rule.source} | ${rule.beforeViolations} | ${rule.afterViolations} | ${rule.resolved ? "yes" : "no"} | ${rule.evidenceRefs.length} |`
      )
    )
    .join("\n");

  return `# SplunkReady Compiler Diagnostics

Generated by: Agent Readiness Compiler

## Summary

- Status: ${diagnostics.status}
- Suite: ${diagnostics.suite.title}
- Mode: fixture
- Mutation: false
- Pass/fail authority: ${diagnostics.passFailAuthority}
- Active deterministic rules: ${diagnostics.totals.activeRules}
- Before violations: ${diagnostics.totals.beforeViolations}
- After violations: ${diagnostics.totals.afterViolations}
- Resolved rules: ${diagnostics.totals.resolvedRules}
- Evidence refs after patch: ${diagnostics.totals.evidenceRefsAfterPatch}
- Trace refs after patch: ${diagnostics.totals.traceRefsAfterPatch}

## Advisory Boundary

Allowed advisory roles:
${diagnostics.advisoryOnly.allowedRoles.map((role) => `- ${role}`).join("\n")}

Prohibited roles:
${diagnostics.advisoryOnly.prohibitedRoles.map((role) => `- ${role}`).join("\n")}

## Rule Outcomes

| Mission | Rule | Severity | Source | Before | After | Resolved | Evidence refs |
|---|---:|---:|---:|---:|---:|---:|---:|
${rows}
`;
};

const loadMissionDiagnostics = async (mission: SuiteProofMissionSummary): Promise<SuiteCompilerMissionDiagnostics> => {
  const profile = readinessProfileSchema.parse(
    await readJson<unknown>(join(mission.artifactDir, "readiness-profile.json"), "readiness profile")
  );
  const beforeReceipt = readinessReceiptSchema.parse(
    await readJson<unknown>(join(mission.artifactDir, "receipt-before-001.json"), "before receipt")
  );
  const afterReceipt = readinessReceiptSchema.parse(
    await readJson<unknown>(join(mission.artifactDir, "receipt-after-001.json"), "after receipt")
  );
  const beforeViolations = violationSchema
    .array()
    .parse(await readJson<unknown>(join(mission.artifactDir, "violations-before.json"), "before violations"));
  const afterViolations = violationSchema
    .array()
    .parse(await readJson<unknown>(join(mission.artifactDir, "violations-after.json"), "after violations"));
  const beforeCounts = countViolationsByRule(beforeViolations);
  const afterCounts = countViolationsByRule(afterViolations);
  const ruleOutcomes = profile.ruleBindings.map((binding): SuiteCompilerRuleOutcome => {
    const beforeCount = beforeCounts.get(binding.ruleId) ?? 0;
    const afterCount = afterCounts.get(binding.ruleId) ?? 0;

    return {
      ruleId: binding.ruleId,
      severity: binding.severity,
      source: binding.source,
      beforeViolations: beforeCount,
      afterViolations: afterCount,
      resolved: beforeCount > 0 && afterCount === 0,
      contractRefs: binding.contractRefs,
      missionRefs: binding.missionRefs,
      evidenceRefs: binding.evidence.map((item) => item.ref),
      rationale: binding.rationale
    };
  });

  return {
    missionId: mission.missionId,
    title: mission.title,
    domain: mission.domain,
    artifactDir: mission.artifactDir,
    proofLoop: mission.proofLoop,
    readinessProfileId: profile.id,
    contractRef: profile.contractRef,
    deploymentSignals: profile.deploymentSignals,
    before: {
      verdict: beforeReceipt.verdict,
      score: beforeReceipt.score,
      violations: beforeViolations.length,
      traceRefs: beforeReceipt.traceRefs.length,
      evidenceRefs: beforeReceipt.evidenceRefs.length
    },
    after: {
      verdict: afterReceipt.verdict,
      score: afterReceipt.score,
      violations: afterViolations.length,
      traceRefs: afterReceipt.traceRefs.length,
      evidenceRefs: afterReceipt.evidenceRefs.length
    },
    activeRules: profile.ruleBindings.length,
    ruleOutcomes
  };
};

export const writeSuiteCompilerDiagnostics = async (input: {
  outDir: string;
  summary: SuiteProofSummary;
  generatedAt: string;
}): Promise<string[]> => {
  const missions = await Promise.all(input.summary.missions.map((mission) => loadMissionDiagnostics(mission)));
  const firstProfile = missions[0]
    ? readinessProfileSchema.parse(
        await readJson<unknown>(join(missions[0].artifactDir, "readiness-profile.json"), "readiness profile")
      )
    : undefined;
  const activeRules = uniqueStrings(missions.flatMap((mission) => mission.ruleOutcomes.map((rule) => rule.ruleId)));
  const resolvedRules = uniqueStrings(
    missions.flatMap((mission) => mission.ruleOutcomes.filter((rule) => rule.resolved).map((rule) => rule.ruleId))
  );
  const diagnostics: SuiteCompilerDiagnostics = {
    source: "splunkready-suite-compiler-diagnostics",
    generatedAt: input.generatedAt,
    compiler: "Agent Readiness Compiler",
    status: input.summary.status,
    mode: "fixture",
    mutation: false,
    suite: {
      id: input.summary.suiteId,
      title: input.summary.suiteTitle,
      path: input.summary.suitePath,
      missionCount: input.summary.missionCount,
      domains: input.summary.domains
    },
    passFailAuthority: "deterministic-rule-engine",
    advisoryOnly: {
      allowedRoles: firstProfile?.llmUsage.allowedRoles ?? [],
      prohibitedRoles: firstProfile?.llmUsage.prohibitedRoles ?? []
    },
    totals: {
      activeRules: activeRules.length,
      beforeViolations: missions.reduce((total, mission) => total + mission.before.violations, 0),
      afterViolations: missions.reduce((total, mission) => total + mission.after.violations, 0),
      resolvedRules: resolvedRules.length,
      evidenceRefsAfterPatch: missions.reduce((total, mission) => total + mission.after.evidenceRefs, 0),
      traceRefsAfterPatch: missions.reduce((total, mission) => total + mission.after.traceRefs, 0)
    },
    missions
  };
  const jsonPath = join(input.outDir, "compiler-diagnostics.json");
  const markdownPath = join(input.outDir, "compiler-diagnostics.md");

  await writeJson(jsonPath, diagnostics);
  await writeText(markdownPath, diagnosticsMarkdown(diagnostics));

  return [jsonPath, markdownPath];
};
