import { readFile, rm, writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";

import type { CertificationIndex } from "./certification-index.js";
import type { LlmProofSummary, LlmProofStatus } from "./llm-proof.js";
import type { ProofManifestVerification } from "./proof-manifest.js";
import type { ProofAuditReport, ProofAuditStatus } from "./proof-audit.js";

export interface JudgeProofLlmEvidence {
  status: "NOT_REQUESTED" | "NOT_CONFIGURED" | LlmProofStatus;
  role: "trace-producer";
  passFailAuthority: "deterministic-rule-engine";
  proofDir: string;
  summaryPath?: string;
  artifacts: string[];
  reason?: string;
  nextCommand: string;
}

export interface JudgeProofSummary {
  source: "splunkready-judge-proof";
  status: ProofAuditStatus;
  mode: "fixture";
  mutation: false;
  generatedAt: string;
  proofDirs: {
    suite: string;
    firewall: string;
    llm?: string;
  };
  gates: Array<{
    id: string;
    status: ProofAuditStatus | ProofManifestVerification["status"];
    artifacts: string[];
  }>;
  llmEvidence: JudgeProofLlmEvidence;
  certificationIndex: string;
  uiArtifacts: string;
  nextCommands: string[];
}

export interface JudgeProofWorkflowInput {
  outDir: string;
  generatedAt: string;
  includeLlmProof: boolean;
  llmProofConfigured: boolean;
}

export interface JudgeProofWorkflowSteps {
  suiteProof(suiteDir: string): Promise<string[]>;
  suiteAudit(suiteDir: string): Promise<string[]>;
  suiteManifest(suiteDir: string): Promise<string[]>;
  firewallCheck(firewallDir: string): Promise<string[]>;
  firewallManifest(firewallDir: string): Promise<string[]>;
  certificationIndex(input: { proofDirs: string[] }): Promise<string[]>;
  llmProof(llmProofDir: string): Promise<string[]>;
}

export interface JudgeProofWorkflowResult {
  artifacts: string[];
  summary: JudgeProofSummary;
}

const readJson = async <T>(filePath: string, label: string): Promise<T> => {
  try {
    return JSON.parse(await readFile(filePath, "utf8")) as T;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);

    throw new Error(`Unable to read ${label} at ${filePath}: ${message}`);
  }
};

const writeJson = async (filePath: string, value: unknown): Promise<void> => {
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
};

const writeText = async (filePath: string, value: string): Promise<void> => {
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, value.endsWith("\n") ? value : `${value}\n`, "utf8");
};

export const cleanJudgeProofArtifacts = async (outDir: string): Promise<void> => {
  await Promise.all([
    rm(join(outDir, "suite-proof"), { recursive: true, force: true }),
    rm(join(outDir, "firewall-check"), { recursive: true, force: true }),
    rm(join(outDir, "llm-proof"), { recursive: true, force: true }),
    rm(join(outDir, "judge-proof-summary.json"), { force: true }),
    rm(join(outDir, "judge-proof-summary.md"), { force: true }),
    rm(join(outDir, "certification-index.json"), { force: true }),
    rm(join(outDir, "ui-artifacts.json"), { force: true })
  ]);
};

const buildLlmEvidence = async (
  input: JudgeProofWorkflowInput,
  steps: JudgeProofWorkflowSteps,
  llmProofDir: string
): Promise<JudgeProofLlmEvidence> => {
  const nextCommand = `npm run splunkready -- judge-proof --out ${input.outDir} --include-llm-proof true --json`;

  if (!input.includeLlmProof) {
    return {
      status: "NOT_REQUESTED",
      role: "trace-producer",
      passFailAuthority: "deterministic-rule-engine",
      proofDir: llmProofDir,
      artifacts: [],
      reason: "judge-proof stayed credential-free; pass --include-llm-proof true when GEMINI_API_KEY is available.",
      nextCommand
    };
  }

  if (!input.llmProofConfigured) {
    return {
      status: "NOT_CONFIGURED",
      role: "trace-producer",
      passFailAuthority: "deterministic-rule-engine",
      proofDir: llmProofDir,
      artifacts: [],
      reason: "GEMINI_API_KEY is not configured; no model call was made.",
      nextCommand
    };
  }

  const artifacts = await steps.llmProof(llmProofDir);
  const summaryPath = join(llmProofDir, "llm-proof-summary.json");
  const llmSummary = await readJson<LlmProofSummary>(summaryPath, "LLM proof summary");

  return {
    status: llmSummary.status,
    role: llmSummary.llmRole,
    passFailAuthority: llmSummary.passFailAuthority,
    proofDir: llmProofDir,
    summaryPath,
    artifacts,
    nextCommand
  };
};

export const judgeProofMarkdown = (summary: JudgeProofSummary): string => `# SplunkReady Judge Proof

Generated by: Agent Readiness Compiler

## Summary

- Status: ${summary.status}
- Mode: fixture
- Mutation: false
- Suite proof: ${summary.proofDirs.suite}
- Firewall proof: ${summary.proofDirs.firewall}
- LLM specimen evidence: ${summary.llmEvidence.status}
- LLM role: ${summary.llmEvidence.role}
- Pass/fail authority: ${summary.llmEvidence.passFailAuthority}
- Certification index: ${summary.certificationIndex}
- UI artifacts manifest: ${summary.uiArtifacts}

## Gates

| Gate | Status | Artifacts |
|---|---:|---:|
${summary.gates
  .map((gate) => `| ${gate.id} | ${gate.status} | ${gate.artifacts.length} |`)
  .join("\n")}

## LLM Specimen Evidence

- Status: ${summary.llmEvidence.status}
- Proof dir: ${summary.llmEvidence.proofDir}
${summary.llmEvidence.summaryPath ? `- Summary: ${summary.llmEvidence.summaryPath}\n` : ""}${summary.llmEvidence.reason ? `- Reason: ${summary.llmEvidence.reason}\n` : ""}
## Next Commands

${summary.nextCommands.map((command) => `- \`${command}\``).join("\n")}
`;

export const runJudgeProofWorkflow = async (
  input: JudgeProofWorkflowInput,
  steps: JudgeProofWorkflowSteps
): Promise<JudgeProofWorkflowResult> => {
  await cleanJudgeProofArtifacts(input.outDir);

  const suiteDir = join(input.outDir, "suite-proof");
  const firewallDir = join(input.outDir, "firewall-check");
  const llmProofDir = join(input.outDir, "llm-proof");
  const artifacts: string[] = [];

  const suiteArtifacts = await steps.suiteProof(suiteDir);
  const suiteAuditArtifacts = await steps.suiteAudit(suiteDir);
  const suiteManifestArtifacts = await steps.suiteManifest(suiteDir);
  const suiteAudit = await readJson<ProofAuditReport>(join(suiteDir, "proof-audit.json"), "suite proof audit");
  const suiteManifest = await readJson<ProofManifestVerification>(
    join(suiteDir, "proof-manifest-verification.json"),
    "suite proof manifest verification"
  );

  artifacts.push(...suiteArtifacts, ...suiteAuditArtifacts, ...suiteManifestArtifacts);

  const firewallArtifacts = await steps.firewallCheck(firewallDir);
  const firewallManifestArtifacts = await steps.firewallManifest(firewallDir);
  const firewallAudit = await readJson<ProofAuditReport>(join(firewallDir, "proof-audit.json"), "firewall proof audit");
  const firewallManifest = await readJson<ProofManifestVerification>(
    join(firewallDir, "proof-manifest-verification.json"),
    "firewall proof manifest verification"
  );

  artifacts.push(...firewallArtifacts, ...firewallManifestArtifacts);

  const indexArtifacts = await steps.certificationIndex({ proofDirs: [suiteDir, firewallDir] });
  const index = await readJson<CertificationIndex>(join(input.outDir, "certification-index.json"), "certification index");
  const llmEvidence = await buildLlmEvidence(input, steps, llmProofDir);
  const summaryStatus: ProofAuditStatus = index.status === "PASS" && llmEvidence.status !== "FAIL" ? "PASS" : "FAIL";
  const summaryPath = join(input.outDir, "judge-proof-summary.json");
  const markdownPath = join(input.outDir, "judge-proof-summary.md");
  const summary: JudgeProofSummary = {
    source: "splunkready-judge-proof",
    status: summaryStatus,
    mode: "fixture",
    mutation: false,
    generatedAt: input.generatedAt,
    proofDirs: {
      suite: suiteDir,
      firewall: firewallDir,
      llm: llmProofDir
    },
    gates: [
      { id: "suite-proof", status: suiteAudit.status, artifacts: suiteArtifacts },
      { id: "suite-proof-manifest", status: suiteManifest.status, artifacts: suiteManifestArtifacts },
      { id: "firewall-check", status: firewallAudit.status, artifacts: firewallArtifacts },
      { id: "firewall-check-manifest", status: firewallManifest.status, artifacts: firewallManifestArtifacts },
      { id: "certification-index", status: index.status, artifacts: indexArtifacts }
    ],
    llmEvidence,
    certificationIndex: join(input.outDir, "certification-index.json"),
    uiArtifacts: join(input.outDir, "ui-artifacts.json"),
    nextCommands: [
      "npm run workbench",
      `npm run splunkready -- certification-index --proof-dirs ${suiteDir},${firewallDir} --out ${input.outDir} --require-pass true --json`,
      llmEvidence.nextCommand
    ]
  };

  await writeJson(summaryPath, summary);
  await writeText(markdownPath, judgeProofMarkdown(summary));

  return {
    artifacts: [...new Set([...artifacts, ...indexArtifacts, ...llmEvidence.artifacts, summaryPath, markdownPath])],
    summary
  };
};
