import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, join } from "node:path";

import { parseMissionDefinition, type MissionDefinition } from "../missions/dsl.js";
import { readinessReceiptSchema } from "../schemas/core.js";
import {
  writeSuiteCompilerDiagnostics,
  type SuiteProofMissionSummary,
  type SuiteProofSummary
} from "./compiler-diagnostics.js";
import { classifyProofLoop } from "./proof-audit.js";
import { annotateReceiptChainMetadata } from "./receipt-chain.js";

interface SuiteDefinition {
  id: string;
  title: string;
  missionPaths: string[];
}

export interface SuiteProofWorkflowInput {
  mode: "fixture" | "live";
  suitePath: string;
  outDir: string;
  requireFailToPass: boolean;
  generatedAt: string;
}

export interface SuiteProofMissionStepInput {
  missionPath: string;
  outDir: string;
}

export interface SuiteProofWorkflowSteps {
  compile(input: SuiteProofMissionStepInput): Promise<string[]>;
  evaluate(input: SuiteProofMissionStepInput): Promise<string[]>;
  receiptBefore(input: SuiteProofMissionStepInput): Promise<string[]>;
  rerun(input: SuiteProofMissionStepInput): Promise<string[]>;
  receiptAfter(input: SuiteProofMissionStepInput): Promise<string[]>;
}

export interface SuiteProofWorkflowResult {
  status: SuiteProofSummary["status"];
  artifacts: string[];
  summary: SuiteProofSummary;
}

const readJson = async <T>(filePath: string, label: string): Promise<T> => {
  try {
    return JSON.parse(await readFile(filePath, "utf8")) as T;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);

    throw new Error(`Unable to read ${label} at ${filePath}: ${message}`);
  }
};

const writeJson = async (filePath: string, value: unknown): Promise<void> => {
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
};

const writeText = async (filePath: string, value: string): Promise<void> => {
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, value.endsWith("\n") ? value : `${value}\n`, "utf8");
};

const parseSuiteDefinition = (input: unknown, suitePath: string): SuiteDefinition => {
  if (!input || typeof input !== "object" || Array.isArray(input)) {
    throw new Error(`Suite manifest at ${suitePath} must be a JSON object.`);
  }

  const record = input as Record<string, unknown>;
  const { id, title, missionPaths } = record;

  if (typeof id !== "string" || id.trim().length === 0) {
    throw new Error(`Suite manifest at ${suitePath} must include a non-empty id.`);
  }

  if (typeof title !== "string" || title.trim().length === 0) {
    throw new Error(`Suite manifest at ${suitePath} must include a non-empty title.`);
  }

  if (
    !Array.isArray(missionPaths) ||
    missionPaths.length === 0 ||
    missionPaths.some((missionPath) => typeof missionPath !== "string" || missionPath.trim().length === 0)
  ) {
    throw new Error(`Suite manifest at ${suitePath} must include a non-empty missionPaths string array.`);
  }

  return {
    id,
    title,
    missionPaths: missionPaths.map((missionPath) => (missionPath as string).trim())
  };
};

const loadSuite = async (suitePath: string): Promise<SuiteDefinition> =>
  parseSuiteDefinition(await readJson<unknown>(suitePath, "suite manifest"), suitePath);

const loadMission = async (missionPath: string): Promise<MissionDefinition> =>
  parseMissionDefinition(await readJson<unknown>(missionPath, "mission"));

const suiteMissionPath = (suitePath: string, missionPath: string): string =>
  isAbsolute(missionPath) ? missionPath : join(dirname(suitePath), missionPath);

const suiteProofMarkdown = (summary: SuiteProofSummary): string => {
  const markdownRows = summary.missions
    .map(
      (mission) =>
        `| \`${mission.missionId}\` | ${mission.domain} | ${mission.proofLoop} | ${mission.before.verdict} / ${mission.before.score} | ${mission.after.verdict} / ${mission.after.score} | ${mission.after.evidenceRefs.length} |`
    )
    .join("\n");

  return `# SplunkReady Suite Proof

Generated by: Agent Readiness Compiler

## Summary

- Status: ${summary.status}
- Suite: ${summary.suiteTitle}
- Mode: fixture
- Mutation: false
- Missions: ${summary.missionCount}
- Domains: ${summary.domains.join(", ")}
- Fail-to-pass missions: ${summary.totals.failToPass}
- READY after patch: ${summary.totals.readyAfterPatch}
- Evidence refs after patch: ${summary.totals.evidenceRefs}

## Missions

| Mission | Domain | Proof loop | Before | After | Evidence refs |
|---|---:|---:|---:|---:|---:|
${markdownRows}
`;
};

export const runSuiteProofWorkflow = async (
  input: SuiteProofWorkflowInput,
  steps: SuiteProofWorkflowSteps
): Promise<SuiteProofWorkflowResult> => {
  if (input.mode !== "fixture") {
    throw new Error("suite-proof currently supports fixture mode only; use live-security-proof for live Splunk evidence.");
  }

  const suite = await loadSuite(input.suitePath);
  const missionSummaries: SuiteProofMissionSummary[] = [];
  const artifacts: string[] = [];

  for (const missionPathInput of suite.missionPaths) {
    const missionPath = suiteMissionPath(input.suitePath, missionPathInput);
    const mission = await loadMission(missionPath);
    const missionOutDir = join(input.outDir, mission.id);
    const stepInput = { missionPath, outDir: missionOutDir };
    const compileArtifacts = await steps.compile(stepInput);
    const evaluateArtifacts = await steps.evaluate(stepInput);
    const receiptArtifacts = await steps.receiptBefore(stepInput);
    const rerunArtifacts = await steps.rerun(stepInput);
    const afterReceiptArtifacts = await steps.receiptAfter(stepInput);
    const beforeReceipt = readinessReceiptSchema.parse(
      await readJson<unknown>(join(missionOutDir, "receipt-before-001.json"), "before receipt")
    );
    const afterReceipt = readinessReceiptSchema.parse(
      await readJson<unknown>(join(missionOutDir, "receipt-after-001.json"), "after receipt")
    );
    const proofLoop = classifyProofLoop(beforeReceipt, afterReceipt);

    missionSummaries.push({
      missionId: mission.id,
      title: mission.title,
      domain: mission.domain,
      artifactDir: missionOutDir,
      proofLoop,
      before: {
        verdict: beforeReceipt.verdict,
        score: beforeReceipt.score,
        violations: beforeReceipt.violations.length
      },
      after: {
        verdict: afterReceipt.verdict,
        score: afterReceipt.score,
        violations: afterReceipt.violations.length,
        evidenceRefs: afterReceipt.evidenceRefs
      }
    });
    artifacts.push(...compileArtifacts, ...evaluateArtifacts, ...receiptArtifacts, ...rerunArtifacts, ...afterReceiptArtifacts);
  }

  await annotateReceiptChainMetadata(input.outDir);

  const domains = [...new Set(missionSummaries.map((mission) => mission.domain))].sort();
  const summary: SuiteProofSummary = {
    status: missionSummaries.every((mission) => mission.after.verdict === "READY") ? "PASS" : "FAIL",
    mode: "fixture",
    mutation: false,
    suiteId: suite.id,
    suiteTitle: suite.title,
    suitePath: input.suitePath,
    missionCount: missionSummaries.length,
    domains,
    totals: {
      failToPass: missionSummaries.filter((mission) => mission.proofLoop === "fail-to-pass").length,
      readyAfterPatch: missionSummaries.filter((mission) => mission.after.verdict === "READY").length,
      evidenceRefs: missionSummaries.reduce((total, mission) => total + mission.after.evidenceRefs.length, 0)
    },
    missions: missionSummaries
  };
  const summaryPath = join(input.outDir, "suite-proof-summary.json");
  const markdownPath = join(input.outDir, "suite-proof-summary.md");

  await writeJson(summaryPath, summary);
  await writeText(markdownPath, suiteProofMarkdown(summary));

  const diagnosticsArtifacts = await writeSuiteCompilerDiagnostics({
    outDir: input.outDir,
    summary,
    generatedAt: input.generatedAt
  });

  if (summary.status !== "PASS") {
    throw new Error(`suite-proof failed. Inspect ${summaryPath}.`);
  }

  if (input.requireFailToPass && summary.totals.failToPass !== summary.missionCount) {
    throw new Error(
      `suite-proof strict fail-to-pass gate failed: ${summary.totals.failToPass}/${summary.missionCount} missions were fail-to-pass. Inspect ${summaryPath}.`
    );
  }

  return {
    status: summary.status,
    artifacts: [...new Set([...artifacts, summaryPath, markdownPath, ...diagnosticsArtifacts])],
    summary
  };
};
