import { scoreMissionSuite, type MissionSuiteScore } from "../grader/scoring.js";
import {
  readinessReceiptSchema,
  type EnvironmentContract,
  type Mission,
  type ReadinessReceipt,
  type TraceEvent,
  type Violation
} from "../schemas/core.js";

export interface ReceiptAgent {
  name: string;
  version: string;
}

export interface PolicyPatchSummary {
  id: string;
  status: string;
}

export interface GenerateReceiptInput {
  id: string;
  agent: ReceiptAgent;
  environment: EnvironmentContract;
  missionSuiteVersion: string;
  missions: Mission[];
  traceEvents: TraceEvent[];
  violations: Violation[];
  policyPatchSummary?: PolicyPatchSummary[];
  rerunComparison?: Record<string, unknown>;
  generatedBy?: string;
  notes?: string;
}

export interface GeneratedReceipt {
  receipt: ReadinessReceipt;
  suiteScore: MissionSuiteScore;
  markdown: string;
  json: string;
}

const unique = (values: string[]): string[] => [...new Set(values.filter((value) => value.length > 0))];

const traceRefsFrom = (traceEvents: TraceEvent[], violations: Violation[]): string[] =>
  unique([...traceEvents.map((event) => event.id), ...violations.map((violation) => violation.traceEventId)]);

const evidenceRefsFrom = (traceEvents: TraceEvent[], violations: Violation[]): string[] =>
  unique([
    ...traceEvents.flatMap((event) => event.evidenceRefs),
    ...violations.flatMap((violation) => violation.evidenceRefs ?? [])
  ]);

const violationById = (violations: Violation[]): Map<string, Violation> =>
  new Map(violations.map((violation) => [violation.id, violation]));

const markdownList = (values: string[]): string => values.map((value) => `- \`${value}\``).join("\n");

const renderMissionTable = (suiteScore: MissionSuiteScore): string => {
  const rows = suiteScore.missionScores.map(
    (missionScore) =>
      `| \`${missionScore.missionId}\` | ${missionScore.verdict} | ${missionScore.score} | ${missionScore.violationIds.length} |`
  );

  return ["| Mission | Verdict | Score | Violations |", "|---|---:|---:|---:|", ...rows].join("\n");
};

const renderCriticalIssues = (receipt: ReadinessReceipt, violations: Violation[]): string => {
  const violationsById = violationById(violations);
  const lines = receipt.criticalViolations.map((violationId) => {
    const violation = violationsById.get(violationId);

    if (!violation) {
      return `- \`${violationId}\` - missing violation record.`;
    }

    const evidenceRefs = violation.evidenceRefs?.length ? ` Evidence: ${violation.evidenceRefs.map((ref) => `\`${ref}\``).join(", ")}.` : "";

    return `- \`${violation.id}\` (${violation.ruleId}) on trace \`${violation.traceEventId}\`: ${violation.reason}${evidenceRefs}`;
  });

  return lines.length > 0 ? lines.join("\n") : "- None.";
};

const renderViolationDetails = (violations: Violation[]): string =>
  violations
    .map((violation) => {
      const evidenceRefs = violation.evidenceRefs?.length
        ? ` Evidence refs: ${violation.evidenceRefs.map((ref) => `\`${ref}\``).join(", ")}.`
        : "";

      return `- \`${violation.id}\` ${violation.severity} ${violation.ruleId}, trace \`${violation.traceEventId}\`: ${violation.reason}${evidenceRefs}`;
    })
    .join("\n");

const renderPolicyPatchSummary = (receipt: ReadinessReceipt): string =>
  receipt.policyPatchSummary.length > 0
    ? receipt.policyPatchSummary.map((patch) => `- \`${patch.id}\` - ${patch.status}`).join("\n")
    : "- None.";

export const renderReceiptMarkdown = (
  receipt: ReadinessReceipt,
  suiteScore: MissionSuiteScore,
  violations: Violation[]
): string => {
  const rerunComparison = JSON.stringify(receipt.rerunComparison, null, 2);
  const violationDetails = renderViolationDetails(violations);

  return [
    `# Readiness Receipt: ${receipt.id}`,
    "",
    `Generated by: ${receipt.generatedBy ?? "Agent Readiness Compiler"}`,
    "",
    "## Summary",
    "",
    `- Agent: ${receipt.agent.name} ${receipt.agent.version}`,
    `- Environment: ${receipt.environment.name} (\`${receipt.environment.id}\`)`,
    `- Mode: ${receipt.mode}`,
    `- Contract version: ${receipt.contractVersion}`,
    `- Mission suite: ${receipt.missionSuiteVersion}`,
    `- Verdict: ${receipt.verdict}`,
    `- Score: ${receipt.score}`,
    ...(receipt.notes ? ["", "## Notes", "", receipt.notes] : []),
    "",
    "## Score Explanation",
    "",
    suiteScore.explanation,
    "",
    ...suiteScore.missionScores.flatMap((missionScore) => [
      `- \`${missionScore.missionId}\`: ${missionScore.explanation}`,
      ...(missionScore.breakdown.blockers.length > 0
        ? missionScore.breakdown.blockers.map((blocker) => `  - Blocker: ${blocker}`)
        : [])
    ]),
    "",
    "## Mission Results",
    "",
    renderMissionTable(suiteScore),
    "",
    "## Critical Issues",
    "",
    renderCriticalIssues(receipt, violations),
    "",
    "## Violations",
    "",
    violationDetails.length > 0 ? violationDetails : "- None.",
    "",
    "## Provenance",
    "",
    "Trace refs:",
    markdownList(receipt.traceRefs),
    "",
    "Evidence refs:",
    receipt.evidenceRefs.length > 0 ? markdownList(receipt.evidenceRefs) : "- None.",
    "",
    "Violation refs:",
    receipt.violations.length > 0 ? markdownList(receipt.violations) : "- None.",
    "",
    "## Policy Patch Summary",
    "",
    renderPolicyPatchSummary(receipt),
    "",
    "## Rerun Comparison",
    "",
    `\`\`\`json\n${rerunComparison}\n\`\`\``
  ].join("\n");
};

export const generateReadinessReceipt = (input: GenerateReceiptInput): GeneratedReceipt => {
  const suiteScore = scoreMissionSuite(input.missions, input.violations);
  const receipt = readinessReceiptSchema.parse({
    id: input.id,
    agent: input.agent,
    environment: { id: input.environment.id, name: input.environment.name },
    mode: input.environment.mode,
    contractVersion: input.environment.version,
    missionSuiteVersion: input.missionSuiteVersion,
    verdict: suiteScore.verdict,
    score: suiteScore.score,
    passedMissions: suiteScore.passedMissions,
    failedMissions: suiteScore.failedMissions,
    criticalViolations: suiteScore.criticalViolationIds,
    violations: input.violations.map((violation) => violation.id),
    traceRefs: traceRefsFrom(input.traceEvents, input.violations),
    evidenceRefs: evidenceRefsFrom(input.traceEvents, input.violations),
    policyPatchSummary: input.policyPatchSummary ?? [],
    rerunComparison: input.rerunComparison ?? {},
    generatedBy: input.generatedBy ?? "Agent Readiness Compiler",
    notes: input.notes
  });
  const markdown = renderReceiptMarkdown(receipt, suiteScore, input.violations);

  return {
    receipt,
    suiteScore,
    markdown,
    json: JSON.stringify(receipt, null, 2)
  };
};
